name: Rebuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v4
      - name: Render template
        run: |
          make -B
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'README.md: rebuild'
          status_options: '--untracked-files=no'
